# Feature Engineering

## Objective

Feature Engineering is the process of preparing the dataset for machine learning models.

In this notebook, we will:

- Select input and output features
- Encode categorical variables
- Scale numerical features (if required)
- Create feature matrix (X) and target variable (y)
- Save the processed dataset

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("../data/cleaned_insurance.csv")

df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# Check Dataset

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   str
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   str
 5   region    1337 non-null   str
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 94.4 KB

# Encode Categorical Features

Machine Learning models require numerical values.

We will convert the categorical columns into numerical values using Label Encoding.

In [4]:
label_encoder = LabelEncoder()

In [5]:
df["sex"] = label_encoder.fit_transform(df["sex"])

df["smoker"] = label_encoder.fit_transform(df["smoker"])

df["region"] = label_encoder.fit_transform(df["region"])

df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

# Verify Encoded Dataset

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   int64
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   int64
 5   region    1337 non-null   int64
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(5)
memory usage: 73.2 KB

# Feature Selection

Separate the input features (X) and the target variable (y).

In [7]:
X = df.drop("charges", axis=1)

y = df["charges"]

In [8]:
print("Input Features (X)")
X.head()

Input Features (X)

   age  sex     bmi  children  smoker  region
0   19    0  27.900         0       1       3
1   18    1  33.770         1       0       2
2   28    1  33.000         3       0       2
3   33    1  22.705         0       0       1
4   32    1  28.880         0       0       1

In [9]:
print("Target Variable (y)")
y.head()

Target Variable (y)

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

# Feature Scaling

StandardScaler standardizes numerical features.

This step is useful for algorithms such as Linear Regression and Gradient Boosting.

In [10]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [11]:
X_scaled

array([[-1.44041773, -1.00977099, -0.45315959, -0.90923416,  1.96966039,
         1.34316271],
       [-1.51164747,  0.99032355,  0.50942165, -0.07944162, -0.50770174,
         0.43801727],
       [-0.79935006,  0.99032355,  0.3831546 ,  1.58014347, -0.50770174,
         0.43801727],
       ...,
       [-1.51164747, -1.00977099,  1.01448983, -0.90923416, -0.50770174,
         0.43801727],
       [-1.29795825, -1.00977099, -0.79752426, -0.90923416, -0.50770174,
         1.34316271],
       [ 1.55123139, -1.00977099, -0.26129928, -0.90923416,  1.96966039,
        -0.46712816]], shape=(1337, 6))

In [12]:
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

X_scaled.head()

        age       sex       bmi  children    smoker    region
0 -1.440418 -1.009771 -0.453160 -0.909234  1.969660  1.343163
1 -1.511647  0.990324  0.509422 -0.079442 -0.507702  0.438017
2 -0.799350  0.990324  0.383155  1.580143 -0.507702  0.438017
3 -0.443201  0.990324 -1.305052 -0.909234 -0.507702 -0.467128
4 -0.514431  0.990324 -0.292456 -0.909234 -0.507702 -0.467128

# Save Processed Dataset

The encoded dataset is saved for model building.

In [13]:
encoded_df = X.copy()

encoded_df["charges"] = y

In [14]:
encoded_df.to_csv("../data/encoded_insurance.csv", index=False)

print("Encoded dataset saved successfully!")

Encoded dataset saved successfully!

In [15]:
encoded_df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520